name: Output Event Details
on:
  issues:
    types: [opened]
jobs:
  Log:
  runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: output event details
        run: echo "${{ toJSON(github)}}"
